version: "2"

services:
  fibon-api:
    image: spetz/fibon-api:latest
    links:
      - rabbitmq
      - elkx
    ports:
      - '5000:5000'

  fibon-service:
    image: spetz/fibon-service:latest
    links:
      - rabbitmq
      - elkx
    ports:
      - '5050:5050'

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'

  elkx:
    image: sebp/elkx:latest
    volumes:
      - elk-data:/var/lib/elasticsearch
    ports:
      - '5044:5044'
      - '5601:5601'
      - '9200:9200'

volumes:
  elk-data:
    external: false